### ISSUE TITLE
sha256 of docopt does not match

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#41] opened 2018-05-04 18:49 UTC
when installing from `pipfile.lock` with `$ sudo pipenv install --three --dev` i get this error:

```
THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    docopt==0.6.2 from https://www.piwheels.org/simple/docopt/docopt-0.6.2-py2.py3-none-any.whl#sha256=0340515c74203895f92f87702896e45424bf51dc71bf15b4748450f50be04346 (from -r /tmp/pipenv-vf5_eub9-requirements/pipenv-k7_dvsro-requirement.txt (line 1)):
        Expected sha256 49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491
             Got        0340515c74203895f92f87702896e45424bf51dc71bf15b4748450f50be04346
```
can i do anything to workaround?

**Comment by cdubz** [comment] 2018-05-04 20:39
Hmmmm. I can't seem to reproduce this locally. Are you attempting this install on a pi (guessing based on #40)? What versions of `pip` and `pipenv` are installed?

I'm testing on my own Pi now and actually having trouble with this command as well, but not due to hashes. I think pandas does a source build and it seems to be taking a very long time on AR

**Comment by cdubz** [comment] 2018-05-06 04:52
This happens because the Pi uses wheel packages from [piwheels](https://www.piwheels.org/) so the checksums don't match. Using `--skip-lock` resolves this, but ARM has other issues. I'm going to close this issue and keep track in #43.

**Closed by cdubz** 2018-05-06 04:52 UTC
