### ISSUE TITLE
Time conversion issues in Timers

### ISSUE THREAD

**Issue by BenjaminHae** [cdubz/babybuddy#90] opened 2020-01-17 18:13 UTC
When creating a timer, the preset start date is set to 2017-01-20 instead of 2020-01-17:
![image](https://user-images.githubusercontent.com/7386033/72635259-ba160080-395c-11ea-906d-442614ad4149.png)

When using a quick-start timer, the time displayed is correct:
![image](https://user-images.githubusercontent.com/7386033/72635131-5c81b400-395c-11ea-8ad2-d8cea4d20de9.png)

However, when creating an (any) activity from it, the time pre-filled in the corresponding form is also wrong:
![image](https://user-images.githubusercontent.com/7386033/72635372-ff3a3280-395c-11ea-9ffc-c50c9906fc2c.png)

The time in the container is set correctly:
```
root@a7beec84db57:/app# date
Fri Jan 17 18:07:07 UTC 2020
```

My `docker.env` contains this line which may be relevant:
```
TIME_ZONE=Europe/Berlin
```
Removing this line does not change anything.

P.S: Really great application!

**Comment by BenjaminHae** [comment] 2020-01-18 09:35
I've looked into it a bit further. When opening the page for creating a new timer, the code shows the following content for the start time:
`<input type="text" name="start" value="18.01.2020 10:28:00" class="datetimepicker-input form-control" data-target="#datetimepicker_start" required id="id_start"><input type="hidden" name="initial-start" value="2020-01-18 10:28:00" id="initial-id_start">`
For some reason the value set in the `text`-input is not set in the `YYYY-MM-DD` format in the hidden field it is however.

**Comment by BenjaminHae** [comment] 2020-01-18 11:10
I fixed it by setting `USE_L10N` to `False` in `babybuddy/settings/base.py`. I'm now looking for sideeffects.

**Comment by cdubz** [comment] 2020-01-18 13:12
Interesting -- thanks for your debugging work so far. There are some weird issues with datetime stuff because the application primary uses the backend for time but there is also some handling in the frontend. #50 has some more discussion about this. Clearly something that needs to be cleaned up.

The [`USE_L10N`](https://docs.djangoproject.com/en/3.0/ref/settings/#use-l10n) option relates to Django's handling of time localization so it makes sense that changing that value would have some sort of effect here.

I'll see if I can replicate this issue with your settings. I'm thinking maybe there is some handling of date data in the frontend that doesn't account for l10n.

**Comment by cdubz** [comment] 2020-01-19 15:41
@BenjaminHae could you tell me about your overall config? I just noticed the button label in your screenshot is "einreichen" but the other words are not in German. Also, Baby Buddy's German translation uses "senden" for that translation.

I'm not able to reproduce your issue locally, so I'm guessing something else here (the browser?) is taking over date formatting in a way that is breaking the datepicker library Baby Buddy uses.

Relatedly, I have been meaning to test removing that library entirely and changing the datetime field to native HTML to see if that is good enough and easier to manage.

**Comment by cdubz** [comment] 2020-01-20 23:53
@BenjaminHae I think this may be resolved with recent commits to `master`. Give a test and re-open this issue if you still have trouble.

**Comment by BenjaminHae** [comment] 2020-01-21 12:09
With the new image I get the following message on submit:
![image](https://user-images.githubusercontent.com/7386033/72803835-4cfdb600-3c4f-11ea-83eb-cacf39ab0f3f.png)

**Comment by cdubz** [comment] 2020-01-21 13:42
Hmmmm this is strange. I can reproduce this with a fresh deployment, but it will work fine after a restart of the application.

**Closed** 2020-01-21 15:23 UTC
Labels: bug

**Comment by cdubz** [comment] 2020-01-21 15:24
@BenjaminHae thanks for your help troubleshooting. I just pushed a commit that I think takes care of that last bug.
